### ISSUE TITLE
'search_results' into the form replacement list

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1379]
### Expected behaviour

Hide this form from the list.

### Actual behaviour

It seems that the form "search_results" still appears into the form replacement list even if we change its form type (e.g. "miscellaneous").

Please Devs, to be confirmed.

### Steps to reproduce

Change the type of this form then check the form replacement list from the "Write" panel.

#### Additional information

Textpattern version: 4.7.2

**Comment by bloatware** [comment]
Can't reproduce, after reload the form is unavailable in "override" selector.

Actually, this form should be essential (not name/type modifiable nor deletable) since it is used by default to output search results.

**Comment by cara-tm** [comment]
Sorry @bloatware, but I can't change the type of these forms.

The purpose of the "Override Form" is to allow writers to choose alternative display for their articles. IMHO, Keeping this 2 models: "article_listing" and "search_results" into this list can't be relevant.

(Textpattern 4.7.2)

![override-form](https://user-images.githubusercontent.com/61045/50371755-63a38a80-05c1-11e9-9bac-95f70aea074a.png)

**Comment by cara-tm** [comment]
The two forms are present below the "Misc" list but still appear into the "Override Form" list. I can't understand.
Note: my install of TXP was a dev one upgraded to 4.7.2 stable version (may be it's the raison why?).

**Comment by bloatware** [comment]
Dunno, I have retested on Pete's demo site and it works like I described above. Mystery.

**Comment by cara-tm** [comment]
Yep, mystery 😂

**Comment by phiw13** [comment]
Out of curiosity, I checked couple of installs. Really puzzling - one install,  still at TXP 4.7.1 with MySQL 5.6 it works as @bloatware describes; Same on one local install, dev, freshly created site, MySql 8. Another local install  on a different machine with MySql 5.7, my “age old“ playground fails - i move the `search_result` form to the `Misc` group, but it still show up on the override form widget.

**Comment by cara-tm** [comment]
Thank you lot @phiw13! I started to go crazy...

**Comment by cara-tm** [comment]
Some new info:
It seems that the list is now corrected and that all items have been reorganized. Can we suspect a database behavior (after optimization with phpMyAdmin) and/or an unexpected Ajax process? (to confirm).

**Comment by cara-tm** [comment]
I noticed another behaviour: deleting a form model do not remove the corresponding file from the theme package. Please devs: try it before to confirm.

**Comment by Bloke** [comment]
That's by design. You can only delete files:

a) From the Themes panel if you check the 'delete unused assets' box when exporting to disk.
b) By hand via your SFTP/SSH client.

The ability to directly export to disk from the Pages/Forms/Styles panels is just a convenience to save you having to keep visiting the Themes panel and doing it there.

**Comment by cara-tm** [comment]
Ok. Fine.

**Comment by philwareham** [comment]
Is this issue resolved now? Ta!

**Comment by Bloke** [comment]
No, it's a bug. `form_pop()` isn't taking the skin into account. I'll fix it.

**Comment by Bloke** [comment]
45f4f70e should have fixed this. The problem was that the override form dropdown was listing _all_ forms. If you made two themes, A and B, and reassigned the `search_results` form in Theme B to the misc group, you would still see it in the list on the Write panel, even though it looked like it had been moved.

What this commit does is take the currently selected section into account. It looks up which _live_ theme is in use by the selected section and only fetches forms from that theme. When you alter the section dropdown, the override_forms stay in step with those available.

Now, this has a few ramifications:

1) If you have an override form in use, and you then select a section that does *not* have that form available, the override form will default to 'none' (empty).
2) If you have a set a section to use a development theme, the forms will still be fetched from the live theme assigned to it. Does that make sense? I think so, because if you edit an article that's in Section 'about' (in Theme A) then you don't want the override forms to suddenly switch to the list of forms in the assigned dev theme... or do we?
3) There's a bit of duplicate code going on inside `article_section_change()` and `form_pop()`. Refactorisation welcome to keep things more DRY.

@cara-tm and others: please take it for a spin and check it works as expected. Sorry for taking so long to fix this.

@bloatware Please check my JavaScript. I'm not sure that returning a comma-separated list of form names in a JSON field is the best way to handle it, but I struggled getting it to return a set of nodes that I could iterate over (in either XML or JSON).

One thing at the back of my mind here is that since this commit adds a section selector hook, it might be nice to expose this as a callback hook for plugins to use. If we handle the callback and JS hook well, then this switcher _might_ prove handy to us/plugin authors when we roll out unlimited CFs.

If there's a way to make this Relay callback chainable/overridable to hand off to some custom plugin code, that'd be awesome. Core could then switch the override forms as it does now, and a plugin could register interest in the same hook and swap out custom fields based on defined sets per section afterwards. Saves reinventing the wheel or them registering their own handlers.

I'm not convinced my JS-fu is up to scratch in this regard, so if anyone has a way of making this new section hook capable of being extended by plugins, now or in future, please tweak the 4.8.2 code so it will be less work for us later.

Thank you!

**Comment by petecooper** [comment]
From my read on https://github.com/textpattern/textpattern/issues/1379#issuecomment-653814240, OP is fixed.

Closing for now.
