### ISSUE TITLE
permissions on new textpattern/plugins folder: Improve the user experience when updating to 4.8

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1465]
A TXP 4.7 install is humming nicely on a shared server. Due to the Apache/PHP configuration folders need the `777` permission to be writable by PHP/Textpattern (default is `755`).

1. Log in and have a quick look around, a little house keeping, maybe some back up of the (active) theme? Log out.
2. Upload TXP 4.8 beta 2
3. go back to browser tab with the login panel and log in. Eventually force reload before logging in to fetch the fresh TXP resources.

4a. In debug and testing mode, you are greeted with a slightly PHP puzzling message about the `textpattern/plugins` folder (text below). That message follows you on every panel. It boils down to the permission issue. Diagnostics panel and Plugins panel have a TXP warning / error message.

4b. in live mode, the situation is slightly worse: you only are warned on the Diagnostics and Plugin panels. However, on the public site, you get the nasty PHP message (text below) instead of the expected page.

In both cases, the error text is the basically the same:

```
A problem occurred while loading the plugin: etc_pagination -> Warning: mkdir(): Permission denied on line 509
A problem occurred while loading the plugin: etc_pagination -> Warning: file_put_contents(/Users/username/Sites/_txp-dev/textpattern/plugins/etc_pagination/etc_pagination.php): failed to open stream: No such file or directory on line 532

Fatal error: Uncaught Error: Call to undefined function strong() in /Users/username/Sites/_txp-dev/textpattern/lib/txplib_misc.php:1414 Stack trace: #0 /Users/username/Sites/_txp-dev/textpattern/publish.php(192): load_plugins(false, 5) #1 /Users/username/Sites/_txp-dev/index.php(69): include('/Users/username/S...') #2 {main} thrown in /Users/username/Sites/_txp-dev/textpattern/lib/txplib_misc.php on line 1414
```
This test site has 3 plugins, I think it complains about etc_pagination because it is the last one I installed.

Note: if you change the permissions on the plugins folder back to `755` - read only in the server configuration -  only the diagnostics and plugins panel display a message (I think).

**Comment by phiw13** [comment]
For reference, [forum posts](https://forum.textpattern.com/viewtopic.php?pid=321444#p321444) and following (@Bloke  and me).

**Comment by bloatware** [comment]
@phiw13 what is `etc_pagination` load order, lower than 5?

**Comment by phiw13** [comment]
Plugins panel tells me: `etc_ pagination` at version 0.4.7b and order is 3.

**Comment by bloatware** [comment]
Thanks, this explains the 'Fatal error', should be fixed now.

**Comment by phiw13** [comment]
OK, round two.

updating from 4.7 to 4.8.dev latest with 4 plugins installed and active - a Dark theme (mines) is active; Hive would give the same results though. Browser used this time: Firefox latest stable release (to make sure no bits of previous testing is left in caches). 

1/ debug mode, Admin side: 
  :_ Diagnostics and Plugins panels show the expected message
  : on every page load, every panel, there is brief flash, a (hidden) message (view source):

```
plugin_load_error_above<strong>glz_custom_fields</strong>
<br /><!DOCTYPE html>
```
 ::_ on the Front side, you get this message at the top of the page (view source - the message is inserted before the `<doctype />`):

```
The above errors were caused by the plugin:etc_pagination
The above errors were caused by the plugin:com_connect
The above errors were caused by the plugin:pap_comconnect
The above errors were caused by the plugin:glz_custom_fields

```

And on a page where a plugin is actually used (contact page, `com_connect`), the whole rim ram of tag errors (that would be expected, as the plugin is _de-facto_ disabled).


2/ in Live mode, same story for the admin side. The front end does not show the rim ram of tag errors (expected), but does show the plugin load errors at the top. **Interestingly**, this time the message shows raw strings – may want to look at that:

```
plugin_load_error_aboveetc_pagination
plugin_load_error_abovecom_connect
plugin_load_error_abovepap_comconnect
plugin_load_error_aboveglz_custom_fields
```

PS - `glz_custom_fields` has a load order of `9`, which explains the sorting of the plugins, I guess.

**Comment by bloatware** [comment]
Thanks @phiw13, now plugin load errors should be silenced in live mode. The missing string is coming from `mode.ini` file imported only in testing modes.

**Comment by phiw13** [comment]
Sounds good. I still have that site open in Firefox in the state I left it earlier today. I’ll check tomorrow morning to see if any issue pops up.

**Comment by phiw13** [comment]
Everything works fine. In Live mode, no more warning/error/… messages, except on Diagnostics and Plugins panels. In Debug mode, the Admin side shows the error in the familiar debug message block at the top of the page.

PS 1/ Did you intentionally [delete](https://github.com/textpattern/textpattern/commit/71e4d1c9fa0b876b607a151c0c6b884a2cb8c7b8) `.htaccess-dist`?

2/ I never noticed but running the site on a local server in Live mode, Diagnostics reports “You are running a dev version a live server” — or perhaps that was always the case, I always run them in debug mode locally.

The experience is now much better. Thank you. I think this is now fixed.

**Comment by petecooper** [comment]
>PS 1/ Did you intentionally delete .htaccess-dist?

For completeness, restored in https://github.com/textpattern/textpattern/commit/124ded1f766e21c9cb37a1b8558aa6b8568d8cfd

**Comment by petecooper** [comment]
Gonna close this as it appears to be resolved- @phiw13: thank you for the report and ongoing testing, very much appreciated.
